### PR TITLE
Add support for email clients in general using mailto: handler.

### PR DESCRIPTION
**Pull request by mjog**
Adds fallback if the default email handler is not Evolution or
Thunderbird that uses the GAppInfo's built-in support for mailto:
URIs. This adds support for e.g. Geary, both when installed locally and
also when it is itself installed via Flatpak.

* src/email.c (compose_mail): If app info command line neither contains
  thunderbird or evolution, use a default mailto: URI handler.

### CODE REVIEW

**Comment by matthiasclasen** [comment]
It does not work 'in general' the syntax of mailto: uris, in particular when it comes to attachments, is sadly far from universal.

**Comment by mjog** [comment]
Sure, but using the mailto handler will enable many more email apps to be used in general than just Evo and Thunderbird, and seems like a better approach than hard-coding in support for every possible email client out there — this started out as an "add support for Geary" patch but realised that it could be easily more widely useful.

So, I can think of a few ways forward here:

1. Keep the patch as-is and file bugs against apps that don't support mailto attachments
2. Use GAppInfo's built-in support for mailto by default unless attachments are specified, in which case fall back to app-specific hacks (and report an error if not supported?)
3. Like (2), but also add a white list of apps that do support mailto attachments
4. Change this back to just "Add support for Geary"
5. Something else?

After thinking about it, I think option (3) is best, but me know which you'd prefer and I'll update the patch as needed.

**Comment by matthiasclasen** [comment]
different email clients expect different escaping for the url, it really is not that simple. I wish it was. The one thing I will merge easily is your 4: add support for geary.

**Comment by matthiasclasen** [comment]
Merging this anyway, we can narrow it down if we get reports of problems with particular clients.

**Pull request merged**
