### PR TITLE
build: require x11 for remote display monitor

### PR DESCRIPTION
**Pull request by amigadave**

### CODE REVIEW

**Comment by amigadave** [comment]
This is a bit ugly, with the gtk+-x11-3.0 check later on, but fixes the build.

**Comment by heftig** [comment]
Also stumbled on this problem and a similar solution: I added the `x11` dep to `GTK_X11`:

```diff
diff --git a/configure.ac b/configure.ac
index 88a9cba..b532412 100644
--- a/configure.ac
+++ b/configure.ac
@@ -61,7 +61,7 @@ PKG_CHECK_MODULES(GTK, [xdg-desktop-portal >= 1.0 glib-2.0 >= 2.44 gio-unix-2.0
 AC_SUBST(GTK_CFLAGS)
 AC_SUBST(GTK_LIBS)
 
-PKG_CHECK_MODULES(GTK_X11, gtk+-x11-3.0,
+PKG_CHECK_MODULES(GTK_X11, [gtk+-x11-3.0 x11],
 		  have_gtk_x11=yes, have_gtk_x11=no)
 if test "$have_gtk_x11" = "yes"; then
 	AC_DEFINE(HAVE_GTK_X11, 1, [define if we we have gtk+-x11])
```

**Comment by amigadave** [comment]
The problem with adding the check alongside gtk+-x11-3.0 is that libX11 is required, as the remote display monitor code is not behind the GTK_X11 conditional. The ugliness that I alluded to previously is that the remote display monitor uses the gdkx.h header, so it probably should be behind that conditional.

**Comment by matthiasclasen** [comment]
That code is going to disappear before too long.

**Comment by matthiasclasen** [comment]
and now it did

**Pull request closed without merging**
