### PR TITLE
fix: missing to add define to c file

### PR DESCRIPTION
**Pull request by Decodetalkers**
resolve: https://github.com/flatpak/xdg-desktop-portal-gtk/issues/453

### CODE REVIEW

**Comment by ebassi** [comment]
Since xdg-desktop-portal-gtk already uses `c_args` in the build, and the symbols are defined only for xdg-desktop-portal-gtk, I'd rather add them to the `c_args`.

**Comment by Decodetalkers** [comment]
Ok.. let me make some changes

**Comment by ebassi** [comment]
See: https://github.com/flatpak/xdg-desktop-portal-gtk/pull/457

**Comment by Decodetalkers** [comment]
Ok , if you have already handle it, then I will close the pr, thanks

**Comment by ebassi** [comment]
Thank you for the pull request, in any case. It's very much appreciated.

**Pull request closed without merging**
