### PR TITLE
configure: Update GTK+ dependency

### PR DESCRIPTION
**Pull request by amigadave**
Depend on at least version 3.16 for gtk_label_set_xalign(). This version
of GTK+ also depends on GLib 2.44, which is the minimum needed for
g_autoptr().

### CODE REVIEW

**Comment by amigadave** [comment]
I came across this while trying to build xdg-desktop-portal-gtk for EPEL7: https://copr-be.cloud.fedoraproject.org/results/amigadave/flatpak-epel7/epel-7-x86_64/00501173-xdg-desktop-portal-gtk/build.log.gz

**Comment by amigadave** [comment]
A few more details:

There are several functions that are from GTK+ 3.16, including gtk_search_entry_handle_event(), gtk_entry_grab_focus_without_selecting() and gtk_css_provider_load_from_resource(). Although GLib 2.46 is included in EPEL7, GTK+ 3.14 is used there, which does not have autoptr support. Therefore, any software built against GTK+ 3 cannot also use autoptr with GTK+ types (such as using G_DECLARE_FINAL_TYPE). It is probably easier to drop the autoptr bits and work around the lack of API if building against GTK+ 3.14 is desired.

**Comment by matthiasclasen** [comment]
yes, lets aim for that

**Comment by amigadave** [comment]
The build passes with these changes, but I haven't tested it yet. Tomorrow!

**Comment by amigadave** [comment]
Oh, it seems that we need to handle gtk_print_job_set_source_fd() as well somehow, which was added in 3.22. I don't think that we have access to the GIOChannel from the outside, so it might be a bit of a challenge.

**Comment by matthiasclasen** [comment]
All the commits look good to me. Wrt to gtk_print_job_set_source_fd(), can we instead dump the contents of the fd in a file and call gtk_print_job_set_source_file() once the file is complete ?

**Pull request merged**
