### PR TITLE
Add I18n support + Spanish translation

### PR DESCRIPTION
**Pull request by mariospr**
Fixes issue https://github.com/flatpak/xdg-desktop-portal-gtk/issues/4

### CODE REVIEW

**Comment by matthiasclasen** [comment]
Lets not use intltool. gettext does all we need nowadays.

**Comment by mariospr** [comment]
I've updated the PR following the lead of GTK+, although I'm not 100% sure yet whether this is exactly what you were looking for. Let me know what you think, thanks!

**Comment by TingPing** [comment]
Should also replace the custom glib macros (`AM_GLIB_GNU_GETTEXT`) with the normal upstream ones (`AM_GNU_GETTEXT`).

**Comment by mariospr** [comment]
@TingPing Thanks for the suggestion. You were right that using those other macros simplify the whole thing quite a lot, and removes the need of the make-pot file. PR updated

**Comment by matthiasclasen** [comment]
make-pot is a special thing that I've added for the GNOME translators; they want to be able to get a git checkout and create a pot file without building. Its not relevant here; we're not on git.gnome.org, and don't get GNOME translations...

**Comment by matthiasclasen** [comment]
Generally looks good to me now; we probably miss a few gettext-domain attributes in .ui files, and we need to call bindtextdomain and bind_textdomain_codeset, but we can fix that up afterwards.

**Comment by mariospr** [comment]
> Generally looks good to me now;

Thanks

> we probably miss a few gettext-domain attributes in .ui files

Looks like you already did that, or is there anything else missing? https://github.com/flatpak/xdg-desktop-portal-gtk/commit/e36256cab0b07668c5456d244c46b16ee2bca6c0

> and we need to call bindtextdomain and bind_textdomain_codeset, but we can fix that up afterwards.

Do you mean https://github.com/flatpak/xdg-desktop-portal-gtk/pull/13/commits/08f19b9c71b4fb6019df0899a31f5ea10e9905f2#diff-6dc2c538ad7ed2c46909a12bac3f96c0R179 ?

**Comment by matthiasclasen** [comment]
Yes,  I think everything is taken care of now

**Pull request merged**
