### PR TITLE
configure.ac: Disable most portals by default

### PR DESCRIPTION
**Pull request by jjardon**
Those portal are now implemented in xdg-desktop-portal-gnome

### CODE REVIEW

**Comment by TingPing** [comment]
Aren't they still used on everywhere not GNOME?

**Comment by jjardon** [comment]
@matthiasclasen I think we want this before GNOME 41 ? https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/1176#note_1188346

**Comment by mcatanzaro** [comment]
We will need to revert this, see https://github.com/flatpak/xdg-desktop-portal/issues/642

**Comment by mcatanzaro** [comment]
Well, we need to bring back the settings and appchooser portals. Otherwise non-GNOME users have no settings and cannot open apps.

I think the other ones are *really* GNOME-specific, and can probably stay disabled.

**Comment by mcatanzaro** [comment]
xdg-desktop-portal-gtk bug report: https://github.com/flatpak/xdg-desktop-portal-gtk/issues/355

**Comment by mcatanzaro** [comment]
> xdg-desktop-portal-gtk bug report: #355

We've caused too much breakage with this change. This *really* needs to be reverted, or at least partially reverted (I *think* it should be sufficient to restore the settings and appchooser portals).

**Comment by mcatanzaro** [comment]
> We've caused too much breakage with this change. This really needs to be reverted, or at least partially reverted (I think it should be sufficient to restore the settings and appchooser portals).

Proposed a fix in #362.

**Pull request merged**
