### PR TITLE
Added Hindi translation

### PR DESCRIPTION
**Pull request by gostsdmitry**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Looks good, but you left some strings marked as "fuzzy". Either you used incorrect translation template (I recommend using the latest one from [Damned Lies](https://l10n.gnome.org)) or there is something wrong with the software you use for your translations.

**Comment by gostsdmitry** [comment]
> Looks good, but you left some strings marked as "fuzzy". Either you used incorrect translation template (I recommend using the latest one from [Damned Lies](https://l10n.gnome.org)) or there is something wrong with the software you use for your translations.

I translated straight to GitHub. The template was the translation file en_GB.po, since there is no pot file here...

**Comment by gostsdmitry** [comment]
You mean this: https://l10n.gnome.org/POT/xdg-desktop-portal-gtk.master/xdg-desktop-portal-gtk.master.pot

**Comment by gostsdmitry** [comment]
@AsciiWolf Look at the translation again, please.

**Comment by AsciiWolf** [comment]
I am on a mobile phone at the moment, but it looks good to me now.

**Comment by gostsdmitry** [comment]
It would be nice if the POT file was in the repository on GitHub...

**Comment by gostsdmitry** [comment]
Is everything correct now?

**Pull request merged**
