### PR TITLE
Gnome-free portals

### PR DESCRIPTION
**Pull request by matthiasclasen**
Make all the portals conditional that have buildtime or runtime GNOME dependencies.

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
Nice work. I understood from our IRC conversation that there would be only one global "enable GNOME" option, would you mind sharing the rationale for going with individual toggles?

**Review by GeorgesStavracas — APPROVED** [review]

**Comment by tinywrkb** [comment]
Working great for me here with Sway compositor and xdg-desktop-portal-wlr.  
I kept the AppChooser and Settings portals enabled as it's not clear to me and this PR does not explain what makes those portals implementations Gnome specific.

**Comment by matthiasclasen** [comment]
> Nice work. I understood from our IRC conversation that there would be only one global "enable GNOME" option, would you mind sharing the rationale for going with individual toggles?

It just turned out that way, no very strong rationale, beyond: "Some of the portals have a build-time dep, others just a runtime one"

One thing I want to still sort out here is a way to influence the preference order for which backend impls to pick in the case that
there are multiple backends installed. We already have that issue currently, with both gnome-shell and xdg-desktop-portal-gtk claiming to support org.freedesktop.impl.portal.Access, and both having UseIn=gnome set. xdg-desktop-portal sorts the portal files alphabetically, so t > n does the right thing for us here.

> I kept the AppChooser and Settings portals enabled as it's not clear to me and this PR does not explain what makes those portals implementations Gnome specific.

Yeah, those are arguably the weakest gnome dependencies of the bunch.

**Comment by tinywrkb** [comment]
@matthiasclasen thanks for replying.

> The settings one depends on the gnome schemas being installed.

Except for the `org.gnome.settings-daemon.*` schemas, the rest are provided by `gsettings-desktop-schemas` which is a dependency of GTK3. The (reverse) dependency tree in my Arch Linux system looks like this `gsettings-desktop-schemas -> glib-networking -> libsoup -> rest -> gtk3`.  
Without `gsettings-desktop-schemas` some things will break when running Flatpak apps, like font antialiasing (flatpak/flatpak#2861 <- note that this is not GTK3 specific, also breaks Chrome), so `gsettings-desktop-schemas` is not specific and maybe should be considered to be a runtime requirement for `xdg-desktop-portal-gtk`.

**Comment by hossamdash** [comment]
is this ready to be merged upstream yet? i would like very much for flatpak application to use my system font config without installing gnome (I'm using xdg-desktop-portal-wlr with sway).

**Comment by hossamdash** [comment]
> 
> 
> Working great for me here with Sway compositor and xdg-desktop-portal-wlr.
> I kept the AppChooser and Settings portals enabled as it's not clear to me and this PR does not explain what makes those portals implementations Gnome specific.
may i ask how you did you build and install this while you have xdg-desktop-portal-wlr installed? I'm under the idea that they both conflict and also maybe you should consider contacting the maintainer of the package on arch to discuss splitting xdg-desktop-portal-gtk into xdg-desktop-portal-gtk (built without gnome and not requiring it ) and xdg-desktop-portal-gnome

**Comment by GeorgesStavracas** [comment]
My understanding is that xdg-desktop-portal picks a portal for each interface, so it would be safe to have both xdg-desktop-portal-gtk and xdg-desktop-portal-gnome installed together - as long as only one portal implementation provides any given interface. If there's conflict, for now, it fallbacks to alphabetical order; e.g. if both xdg-desktop-portal-gtk and xdg-desktop-portal-gnome provide `org.freedesktop.portal.ScreenCast`, it would pick `gnome` before `gtk`.

I think we should instruct distros that will ship xdg-desktop-portal-gnome to disable all GNOME-specific interfaces from xdg-desktop-portal-gtk; and vice-versa.

**Comment by tinywrkb** [comment]
> may i ask how you did you build and install this while you have xdg-desktop-portal-wlr installed? I'm under the idea that they both conflict

@hossamdash there's no filesystem conflict, there never was, so they both can be installed from this aspect.  

There's no runtime conflict because the order in `XDG_CURRENT_DESKTOP` is respected, you just need to set and export it correctly. Note that the split is on colon, not semi-colons.  
You set it to something like `XDG_CURRENT_DESKTOP="sway:GNOME"`, and export it for both your:
* User environment. So `.profile`, `bashrc`, or whatever else you use or your desktop environment supports.
*  systemd user environment. So environment.d or specific `Environement=` override for `xdg-desktop-portal.service`.

I'm not sure that the split on a colon is properly documented. Some apps don't implement this properly so you need to work around this, which is easy if you're using Flatpak, just need a simple environment override.  
Flameshot is a good example of an app that had that fixed recently, still broken in the latest stable release but working in master.  

Another example where it's broken is with some QT5 apps that are making use of the StatusNotifierItem protocol, e.g. Insync.  
In this case, your `XDG_CURRENT_DESKTOP` set to `sway:GNOME:Unity"` but this not being respected so you need to override it and set it only to `Unity`.  
It goes without saying that your status bar should support SNI and not only XEmbed.  
This has nothing to do with `xdg-desktop-portal` but should be mentioned.  

> also maybe you should consider contacting the maintainer of the package on arch to discuss splitting xdg-desktop-portal-gtk into xdg-desktop-portal-gtk (built without gnome and not requiring it ) and xdg-desktop-portal-gnome

The current `xdg-desktop-portal-gtk` and `xdg-desktop-portal-wlr` Arch Linux packages work fine together if you properly set `XDG_CURRENT_DESKTOP`.  
The only benefits of adding an `xdg-desktop-portal-gnome` package are to avoid setting a var and avoid install some dependencies.  
I personally don't think these benefits justify another official Arch Linux package, at least not when you cannot create a split package that only has the Gnome-related interfaces and without conflicting files with Gnome-free `xdg-desktop-portal-gtk` package.  
You're welcome to suggest this to the current Arch Linux package maintainer. I won't, I've seen enough of my suggestions for packaging improvements being ignored or rejected so nowadays I just don't bother and maintain my own packages.  

I have an [`xdg-desktop-portal-gtk-gnomefree` packaging here](https://github.com/tinywrkb/pkgbuilds/blob/main/xdg-desktop-portal-gtk-gnomefree/PKGBUILD).  
I won't publish this to the AUR it's linked against my own private GTK3 package.  
You're welcome to publish it in the AUR, you just need to change back the dependency to the official GTK3 package, and as now the PR is merged, you don't need the patch file, you can switch to cherry-picking in the prepare() function.

**Comment by hossamdash** [comment]
@tinywrkb 
I thank you very much for your very thorough explanation which took me a while to wrap my head around but i finally did.
To sum up what you said and make sure i got it right adding the split package xdg-desktop-portal-gtk-gnomefree and using it instead of xdg-desktop-portal-gtk [arch package link](https://archlinux.org/packages/extra/x86_64/xdg-desktop-portal-gtk/) will have the benefits of 
- not needing a dependency which is in the case of Arch Linux is [gnome-desktop](https://archlinux.org/packages/extra/x86_64/gnome-desktop/).
- not needing to set the environment variable `XDG_CURRENT_DESKTOP` for both user and systemd with the various workarounds that you mentioned.

I just built and installed your `PKGBUILD` _(after changing dependency to gtk3)_ which solved a lot of headaches I was having with flatpaks which are so far
- fontconfig finally working
- flatpak gtk applications finally respecting the global theme

with no special configuration whatsoever. I do think this merits a package split in the offical repos and will try to contact the maintainer. as for maintaining an AUR package I'm not really comfortable with the packaging process and the various commands related to it just yet but i will certainly have it in my mind if i do. if I understand correctly right now you pulling the commit of the latest stable release and "cherry picking" the merged commit of this pull request, what's the benefit of doing this instead of building from master?

**Comment by tinywrkb** [comment]
> which solved a lot of headaches I was having with flatpaks which are so far
> 
> * fontconfig finally working
> * flatpak gtk applications finally respecting the global theme

I hope you're importing the relevant environment variables to the dbus user session as explained here: [GTK+ applications take 20 seconds to start](https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start).

> what's the benefit of doing this instead of building from master?

I always prefer to stay close to stable, I haven't planned to test master, though there's not a lot there. All my GUI apps are Flatpaks and I don't like it when things break, let other users be guinea pigs. I can count on one hand the number of `-git` packages that I have installed on my system, and only one is actively developed.  
And maybe more important, less packaging maintenance when staying close to the official package.

>  I do think this merits a package split in the offical repos and will try to contact the maintainer.

The Gnome related portals are planned to be removed so maybe wait a bit, see the gnome-desktop removal PR.  

Anyways, this is not the right place to discuss packaging, we're spamming each one of the subscribers to this repo and this PR. If you have more questions for me then you can reach me via email, it's the same as my nick here but just in Gmail.

**Comment by AdrianVovk** [comment]
Are there plans to remove the gnome-specific parts from here? Or add the per-component switches to x-d-p-gnome?

My DE is very gnome-like, and so anything that doesn't explicitly depend on gnome-shell will work. It'd be nice to disable i.e. screenshot and screencast but have everything else enabled.

**Pull request merged**
