### PR TITLE
Update Czech translation

### PR DESCRIPTION
**Pull request by AsciiWolf**
Remove unnecessary string that was not marked for translation.

### CODE REVIEW

**Comment by mariospr** [comment]
This looks like a mistake, seems that the string should be made translatable instead of removing the already available translation for it, no?

**Comment by AsciiWolf** [comment]
@mariospr Not sure, see piotrdrag's [comment](https://github.com/flatpak/xdg-desktop-portal-gtk/pull/80#issuecomment-306472045).

**Comment by matthiasclasen** [comment]
if you look at the c file, we unconditionally replace the content of the heading label when setting up the dialog. The string is just there as a placeholder. Could be dropped, I guess.

**Comment by AsciiWolf** [comment]
Do not merge this yet; I will push a new commit with some new strings added so I don't have to open a new PR for it. Thanks.

**Comment by mariospr** [comment]
@matthiasclasen Ah, ok. I missed that, thanks for clarifying

@AsciiWolf No problem, just let us know when it's ready

**Comment by AsciiWolf** [comment]
@mariospr Done.

**Comment by mariospr** [comment]
Merged. Thanks and sorry for the confusion yesterday. Let's say I did not have a good day, for many unrelated reasons :), and move on...

**Pull request merged**
