### PR TITLE
Add window screen cast

### LINKED ISSUE #204: Allow Window sharing in the ScreenCast portal
The portal actually has the interface to allow it and some apps (e.g. Chrome) actually support it, so it would be nice to have this implemented in the gtk portal.

### PR DESCRIPTION
**Pull request by albfan**
This fixes #204

### CODE REVIEW

**Comment by albfan** [comment]
I think this needs:
 - code: some review about async from @jadahl 
 -design: text messages by @allanday.
- browsers (bluejeans): review by @tpopela 
   - chrome: this offers the xdg-desktop-portal dialog for windows to share but nothing is seen on chrome dialog
   - firefox: share screen is not seen among options on video meeting
- python script: screen/windows sharing works, but for windows a black border is shown which maybe is not correct and it needs to be only the window:

window sharing

**Comment by jadahl** [comment]
>     * python script: screen/windows sharing works, but for windows a black border is shown which maybe is not correct and it needs to be only the window:

I think this might be due to the pipewire gstreamer source not handling crop rects properly. GNOME Shell will create a larger than the window buffer (the size of the monitor actually IIRC), and then crop the buffer to let the receiving end what part of the buffer is relevant. This is to allow window resizing. @wtay, could that be the case?

**Comment by jadahl** [comment]
> code: some review about async from @jadahl

What is needed is turning `shellintrospect.c` into something similar to https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/src/displaystatetracker.c but for `org.gnome.Shell.Introspect`.

**Comment by albfan** [comment]
>  This is to allow window resizing. 

Makes sense. If I maximize the window it will take the size of the actual screen. That makes me wonder what would happen if I change window to other screen and maximize. Have to try that

**Comment by albfan** [comment]
Closing in favour of #225

**Pull request closed without merging**
