### PR TITLE
Update LINGUAS - add Sloveninan (sl) language

### PR DESCRIPTION
**Pull request by filmsi**
Add the support for Slovenian (sl) language.

### CODE REVIEW

**Comment by TingPing** [comment]
Could you please just add the changes from #488 onto this branch?

**Comment by filmsi** [comment]
I do not know how to do that. I do not use git on my computer.
I am just a translator.

**Comment by filmsi** [comment]
It was ok for xdg-desktop-portal, see:
https://github.com/flatpak/xdg-desktop-portal/pull/1413
https://github.com/flatpak/xdg-desktop-portal/pull/1412

As per comments there, I did commits for this project in reverse order, so first file sl.po is added, then the string "sl" is added to LINGUAS.

**Comment by TingPing** [comment]
You don't need to use git, you can just add the file here: https://github.com/filmsi/xdg-desktop-portal-gtk/tree/patch-1

**Comment by filmsi** [comment]
Is this ok?

**Comment by TingPing** [comment]
Yes, thank you!

**Pull request merged**
